Repository ericahagle/fitlit, pull requests merged in 2023-10, with the labels that each got.

#7 docs: Create pull_request_template.md
  pull_request_template.md
Labels: documentation, setup

#24 Add user object function
  src/domUpdates.js
  src/scripts.js
Labels: user story

#45 Feat/css styling
  dist/bundle.js
  dist/index.html
  src/css/styles.css
  src/scripts.js
Labels: user story

#42 test: Add tests for userObject functionality
  src/scriptDefinitions.js
  src/scripts.js
  test/UserRepository-test.js
  test/domUpdates-test.js
  test/scripts-test.js
Labels: user story

#51 refactor: Remove domUpdates-test.js file because we won't need it
  test/domUpdates-test.js
Labels: setup

#54 test: Add test for findStepGoalAverage function
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#47 Add displayUserInfo dom update
  src/domUpdates.js
Labels: user story

#48 Add a hydrationAverage function and test
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#49 Add a function to find ounces drank on a date
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#50 Add a function that returns hydration for 7 days
  src/scriptDefinitions.js
  test/UserRepository-test.js
  test/scripts-test.js
Labels: user story

#57 Hydration Dom Updates
  src/domUpdates.js
  src/scriptDefinitions.js
Labels: user story, draft

#58 Function/sleep dom updates
  src/domUpdates.js
Labels: user story, draft

#52 feat/reorganize and style css/html
  dist/index.html
  src/css/styles.css
  src/scripts.js
Labels: user story

#63 Function/sleep quality for specific date
  src/scriptDefinitions.js
  test/UserRepository-test.js
  test/scripts-test.js
Labels: user story

#62 Function/hours slept on a given day
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#60 Add a function to calculate average sleep hours
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#61 Function/average sleep quality
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#59 test: Add tests for findDistanceTraveled function
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#64 Function/getSleepfor7 days
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#65 Add an activity DOM function
  src/domUpdates.js
Labels: user story

#66 feat: Hook up APIs
  src/apiCalls.js
  src/scriptDefinitions.js
  src/scripts.js
  test/scripts-test.js
Labels: user story

#70 Add a function to return 7 days sleep quality
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#71 Fixes a bug in the getHydrationFor7Days function
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: bug

#76 Refactor/update current user functionality
  src/apiCalls.js
  src/scriptDefinitions.js
  src/scripts.js
Labels: user story

#77 Function/weekly activity
  src/domUpdates.js
  src/scripts.js
Labels: user story

#74 Bug/sleep for7 days
  test/scripts-test.js
Labels: bug

#79 Add Step Goal Comparison
  src/domUpdates.js
  src/scripts.js
Labels: user story

#78 Function/check step goal
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#75 Function/minutes active given date
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#83 Add sleepLifeUpdate function
  src/domUpdates.js
  src/scripts.js
Labels: user story

#73 refactor: Clean and DRY up tests
  src/data/testData.js
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: enhancement

#87 Adds a function to return reaced step goal each day for a week
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: user story

#92 Fixes import/export of Fetch
  src/apiCalls.js
  src/scripts.js
Labels: bug

#95 fix: Refactor new tests, clean up all tests, and create one new test
  test/scripts-test.js
Labels: enhancement

#82 Refactor/adjust html and css for dom
  dist/index.html
  src/css/styles.css
  src/domUpdates.js
Labels: user story

#100 Refactor/html accessibility
  dist/index.html
Labels: enhancement

#97 Add to the checkStepGoal7Days function to include daily steps
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: enhancement

#102 Fix/fix goal7 days
  src/domUpdates.js
  src/scripts.js
Labels: bug

#106 data: Remove hard-coded data files now that we're using apis
  src/data/hydration.js
  src/data/users.js
Labels: setup

#103 docs/README final cleanup
  README.md
Labels: documentation

#104 Refactor/styling final pass
  dist/index.html
  src/css/styles.css
  src/domUpdates.js
  src/scripts.js
Labels: user story
