Repository ericahagle/fitlit, pull requests merged in 2023-11, with the labels that each got.

#122 Adds all API endpoints
  src/apiCalls.js
Labels: user story

#123 Add toggle dom function
  dist/index.html
  src/css/styles.css
  src/domUpdates.js
  src/scripts.js
Labels: user story

#124 Adds a a calendar and post event
  dist/index.html
  src/apiCalls.js
  src/css/styles.css
  src/domUpdates.js
  src/scriptDefinitions.js
  src/scripts.js
Labels: user story

#126 Adds the ability to update hydration to the DOM
  src/apiCalls.js
  src/scriptDefinitions.js
  src/scripts.js
Labels: user story

#129 feat: [fitlit #111] Add function to get all data from any given user
  src/scriptDefinitions.js
  test/scripts-test.js
Labels: task

#133 Admin display/jsFunctions
  src/scriptDefinitions.js
  src/scripts.js
Labels: user story

#136 test: Add tests and test data for bottom 10s functions
  src/data/testData.js
  test/scripts-test.js
Labels: task

#130 Display/admin page html
  dist/index.html
  src/css/styles.css
  src/domUpdates.js
  src/scripts.js
Labels: user story

#138 feat: Add event listener to grab user from email search
  src/domUpdates.js
  src/scriptDefinitions.js
  src/scripts.js
Labels: task

#144 docs: Update README with server installation instructions additional tweaks
  README.md
Labels: documentation
